services:
  ppocr-high-performance:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1008:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - custom_network
    entrypoint: >
      bash -c "
        paddleocr install_hpi_deps gpu &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

networks:
  custom_network:
    driver: bridge
    name: ${NETWORK_NAME}